<?php

    $__OneDB_Default_TV_object__ = array(
        'headlines'     => '',
        'croll'         => '',
        'category'      => ''
    );

    require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'OneDB_Article_plugin_TV_object.class.php';

    OneDB_RegisterBackendObject( array(
        'backendName'       => 'TV_object',
        'docType'           => 'TV_object',
        'icon'              => 'data:image/gif;base64,R0lGODlhEAAQAOZEAMzMzNLNxWaZzJnM/3d3d5HE91mMv0R3qkJCQm1tbXV1dU2As4CAgEpKSj1wozY2NoyMjJmZmaamprKysry8vMXFxWNjY19fXzptoDMzM729vYSEhGeazYK16D8/P2OWyXeq3Xx8fEZGRpSUlDo6Om2g01h+pGtra1WIu42NjTdqnVpaWquopHt7e01NTTk5OVVVVZGRkYKAfEd6rXJyckRERF6RxIe67VKFuE9PT1B2nUJ1qEBzpjVom6ioqD09PVyPwsTExLm5uaysrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAEQALAAAAAAQABAAAAfCgESCRBmDg4WGhgSKiY2LRI+GLCc0LRspIwQEIykbLTQnLBYApKWmphYXFSYOC0ACAkALDiYVCBUXKxQ9A72+vT0UQRQrMBMqNwXKyzcqEwgTMDkSGCUcIB0dIBwlGBJCEjkNEQ42B+foNg4RCBENNRA8Hwb09R88EEMQNR4MO7AAAe5gQNADCQU6ZizAgQIFjgUzdCiYSOJBghAxfGggpcFHjBAJQj6Q8eDFDwQiGrhw0UAEgh8vRhIJQLOmTZtEAgEAOw==',
        'defaultNamePrefix' => 'TV_object'
    ) );

?>